### PR TITLE
getTreatments(): get the treatment names from an assignment object serverside

### PR DESCRIPTION
**Pull request by ElliotSalisbury**
I needed to have access to the treatments of the different assignments during the initialization of an instance:

e.g.:
```javascript
TurkServer.Instance.initialize(function () {
        //should only be two users, check the treatments of each user and record which one is blind
        var blindUserId = -1;
        var sightedAssistantId = -1;
        var users = this.instance.users();
        for (var i=0; i<users.length; i++){
            var userId = users[i];
            var assignment = TurkServer.Assignment.getCurrentUserAssignment(userId);
            var treatments = assignment.getTreatments();
            if(treatments.indexOf("blind_treatment") != -1) {
                blindUserId = userId
            }else{
                sightedAssistantId = userId;
            }
        }
}
```

### CODE REVIEW

**Comment by mizzao** [comment]
Thanks. Do you think it is in general more useful to have a structure like this, with just the treatment names, or to actually get the treatment key/value pairs as here: https://github.com/TurkServer/turkserver-meteor/blob/2c6e373e92e73036584eb8c39271f6eb9d97ab52/server/instance.js#L168

**Comment by ElliotSalisbury** [comment]
So when testing this (in the instance initialization)  that function returned empty. 
I assumed it was returning treatments assigned to the instance object, not the assignment objects. 
To me, it didn't make sense that an instance could be assigned a treatment though?

**Comment by mizzao** [comment]
Both instances (a group of people at a particular point in time) and assignments (one person over the course of a task) can be assigned treatments. In the client, these all get merged together and all properties are visible.

This way, you can have treatments both active on "worlds" and "individuals", and determine UX based on some combination of them. The instance treatments may be useful when groups of people get assigned to a different task or interface within the same HIT, for example.

In any case, while accessing these treatments on the server we should come up with a consistent convention for them...or maybe both variants are useful.

**Comment by ElliotSalisbury** [comment]
Okay that makes sense. 
At the moment I think we can only retrieve instance treatments server side. 

What would be the best convention here? 
A TurkServer.getTreatments(assignmentId) call that returns both?

**Comment by mizzao** [comment]
Let's try to hammer the details of a better API out in person when I visit next week.

**Pull request merged**
